### ISSUE TITLE
Use Github Pages

### ISSUE THREAD

**Issue by ratnanil** [kurzmir1/pted_week2#1]
If you want to make turn your Analysis into a website, there are only 3 steps you need to take! Go to https://github.com/kurzmir1/pted_week2/settings/pages  and under 'Source' choose the branch `main` and click 'Save'. Your Analysis is now visible under https://kurzmir1.github.io/pted_week2/week2-rexcercise_task1.html

**Comment by kurzmir1** [comment]
thank you for the tipp!
